/**
 * Shared translation for the backend's `tool_notes` / live-progress
 * `note` strings (see AnalysisToolProgress.note / ToolNotes in
 * src/types/analy.type.ts). These strings are short, human-unfriendly
 * English diagnostics generated by the analysis pipeline when a tool
 * (virustotal/mobsf/cape) is force-skipped after repeated errors or
 * rate-limiting, e.g.:
 *   "VirusTotal skipped after 3 failed attempts: HTTP Error 429"
 *   "CAPE skipped after 40 status checks with no result"
 *
 * Never render these raw strings to end users - always pass them
 * through translateToolNote() first.
 *
 * NOTE for backend authors: matching is substring-based against the
 * patterns below (case-sensitive). Keep generated note strings
 * containing one of these exact substrings so they map to the correct
 * Thai explanation instead of falling back to the generic message.
 */
export function translateToolNote(note: string): string {
  if (note.includes('failed attempts')) {
    return 'ระบบพยายามเชื่อมต่อซ้ำหลายครั้งแต่ไม่สำเร็จ (อาจติด rate limit)'
  }
  if (note.includes('status checks with no result')) {
    return 'เครื่องมือนี้ใช้เวลานานเกินไป ระบบจึงข้ามการวิเคราะห์นี้ไป'
  }
  return 'เครื่องมือนี้พบปัญหาระหว่างวิเคราะห์และถูกข้ามไป'
}

/** Display labels for the tool keys that can appear in ToolNotes. */
export const TOOL_NOTE_LABELS: Record<string, string> = {
  virustotal: 'VirusTotal',
  mobsf: 'MobSF',
  cape: 'CAPE Sandbox',
}
